# Turn off edge scrolling
exec synclient HorizEdgeScroll=0 VertEdgeScroll=0

# Disable Tap-To-Click (1 finger, 2 finger, 3 finger)
exec synclient TapButton1=0 TapButton2=0 TapButton3=0
exec synclient MaxTapTime=0

# Enable Horizontal Scrolling
exec synclient HorizTwoFingerScroll=1

# Enable Two-Finger Right Click
exec synclient ClickFinger2=3

# Scroll Direction (Old School / "Un-natural" / Up Goes Up)
exec synclient VertScrollDelta=247


exec i3
