#!/bin/bash

command=$1

case command in
  to-machine)
    cp ./.vim/autoload ~/.vim/ -R
    cp ./.vim/colors ~/.vim/ -R
    cp ./.vim/vimrc ~/.vim/ -R
    cp .vimrc ~/
  ;;
  to-repo)
    cp ~/.vimrc ./
    cp ~/.vim/autoload ./.vim/ -R
    cp ~/.vim/colors ./.vim/ -R
    cp ~/.vim/vimrc ./.vim/ -R
  ;;
esac
