-- Plug 'akinsho/nvim-bufferline.lua'
--
-- require'bufferline'.setup{
--   options = {
--     -- view = 'multiwindow',
--     always_show_bufferline = false,
--     separator_style = "thin",
--     -- tab_size = 10,
--     show_buffer_close_icons = false,
--     -- enforce_regular_tabs = true
--   }
-- }
