#!/bin/bash
# https://www.reddit.com/r/i3wm/comments/8hpjb6/i3_lock_screen/dyojibp/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage

# https://www.reddit.com/r/unixporn/comments/3358vu/i3lock_unixpornworthy_lock_screen/
temp_file="/tmp/screen.png"
icon="$HOME/scripts/zerg_purple.png"
lock_blur_factor=0
screen_size="$(xdpyinfo | awk '/dimensions/{print $2}')"
wallpaper="$(gsettings get org.gnome.desktop.background picture-uri | sed -e 's/file:\/\///g')"
width="$(echo $screen_size | cut -d 'x' -f 1)"
height="$(echo $screen_size | cut -d 'x' -f 2)"
pixelate=16

ffmpeg -f x11grab \
  -video_size "$screen_size" \
  -y -i $DISPLAY -i $icon \
  -filter_complex "scale=iw/$pixelate:ih/$pixelate,scale=$pixelate*iw:$pixelate*ih:flags=neighbor,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2,boxblur=$lock_blur_factor:$lock_blur_factor" \
  -vframes 1 $temp_file


i3lock --ignore-empty-password --image=$temp_file
rm $temp_file
