#!/bin/bash
#
# Required dependencies
#  - fzf
#
# Usage:
#
#   markdown
#   markdown README
#   PORT=4200 markdown
#   PORT=4200 markdown README
#
# You'll prompted with detected markdown files

if [[ -n "$1" ]]; then
  local QUERY="--query $1"
fi

function find_markdown() {
  ag -g md
}

FILE=$(find_markdown | fzf -1 $QUERY)

if [ -z "$FILE" ]; then
  exit 1;
fi

port="${PORT:-1337}"

read -r -d '' warningMessage <<-EOF
  Start markdown preview server?

    rendering $FILE
    @ localhost:$port

  Confirm? (Y|N)

  NOTE: to start with a custom port set \$PORT
EOF

while true; do
    read -p "$warningMessage" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo ""
echo "$FILE is now live at localhost:$port"
echo ""

npx livedown start $FILE --port $port
