#!/bin/bash
#
# Usage:
#    cat /tmp/error.dump.log | unme | setclip
#
input=$(</dev/stdin)
original_dev="/home/$USER/Development/"
dev="/✂️ /"
original_tilde="/home/$USER/"
tilde="🏠/"

echo $to_remove

echo "$input" | sed "s~$original_dev~$dev~g" | sed "s~$original_tilde~$tilde~g"
