#!/bin/bash

helpers="$(dirname "${BASH_SOURCE[0]}")/-helpers"
currentPath=$(which nvim)
installPath="${currentPath:-/usr/bin/nvim}"
linux_url="https://github.com/neovim/neovil/releases/download/nightly/nvim-linux-x86_64.appimage"
mac_url="https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz"

url="<not set>"


unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*) 
      url=$linux_url
    ;;
    Darwin*)    
      url=$mac_url
      installPath="~/Applications/nvim"
    ;;
    *)    
      echo "Unknown OS: $unameOut"
esac



nvim_local_file=$(basename $url)

source "$helpers/colors.sh"

read -r -d '' warningMsg << EOF
  You are about to download from $url
  once downloaded, the file will replace $installPath

  You will be asked for sudo access to mv the file to $installPath
EOF

"$helpers/warning-prompt.sh" "$warningMsg"

if [ "$?" == "1" ]; then
  exit 1
fi

echo ""
echo ""

# remove any previous downloads
rm -f nvim.appimage > /dev/null 2>&1
rm $nvim_local_file > /dev/null 2>&1

set -e
info "Downloading..."
wget -q $url
echo ""
echo ""


sha_line="$(sha256sum $nvim_local_file)"

sha_msg="
  $sha_line

  Is the SHA256 good?

  verify at https://github.com/neovim/neovim/releases/tag/nightly
"


"$helpers/warning-prompt.sh" "$sha_msg"

if [ "$?" == "1" ]; then
  echo "Cancelling install..."
  exit 1
fi
echo ""
echo ""

if [[ $nvim_local_file == *appimage ]]; then
  info "Making executable -- chmod +x"
  chmod +x $nvim_local_file 

  warn "Moving to $installPath"
  sudo mv $nvim_local_file $installPath
  yay "Success!"
fi

if [[ $nvim_local_file == *tar.gz ]]; then
  info "Untarring via tar -xf"
  tar -xf $nvim_local_file
  folder_name="${nvim_local_file%.*.*}"
  bin_path="$installPath/bin/nvim"

  warn "Deleting old ~/Applications/$folder_name"
  ( cd ~/Applications && rm -rf "./$folder_name" )

  warn "Deleting old ~/Applications/nvim"
  ( cd ~/Applications && rm -f nvim )

  warn "Moving $folder_name to ~/Applications"
  mv $folder_name ~/Applications/$folder_name
  warn "Symlinking $bin_path to ~/Applications/nivm" 
  ln -s $HOME/Applications/$folder_name/bin/nvim $HOME/Applications/nvim
fi



info "You now have $(nvim -v | grep "NVIM v")"
