#!/bin/bash
# by http://github.com/jehiah
# this prints out some branch status (similar to the '... ahead' info you get from git status)

# example:
# $ git branch-status
# dns_check (ahead 1) | (behind 112) origin/master
# master (ahead 2) | (behind 0) origin/master

TOTAL_DIFFERENCES=0
G=$'\e[1;32m'
Y=$'\e[1;33m'
C=$'\e[0;34m'
R=$'\e[1;31m'
E=$'\e[0m'

while read local remote
do
    git rev-list --left-right ${local}...${remote} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
    LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
    RIGHT_BEHIND=$(grep -c '^>' /tmp/git_upstream_status_delta)
    TOTAL_DIFFERENCES=$(($LEFT_AHEAD + $RIGHT_BEHIND + $TOTAL_DIFFERENCES))
    MSG_LEFT_AHEAD="(ahead $LEFT_AHEAD)"
    MSG_RIGHT_BEHIND="(behind $RIGHT_BEHIND)"

    if [ "$LEFT_AHEAD" -ne 0 ]; then
        MSG_LEFT_AHEAD="$Y$MSG_LEFT_AHEAD$E"
    else
        MSG_LEFT_AHEAD="$C$MSG_LEFT_AHEAD$E"

    fi
    if [ "$RIGHT_BEHIND" -ne 0 ]; then
        MSG_RIGHT_BEHIND="$R$MSG_RIGHT_BEHIND$E"
    else
        MSG_RIGHT_BEHIND="$C$MSG_RIGHT_BEHIND$E"
    fi

    printf '%25s| %-25s %-38s %s\n' "$MSG_LEFT_AHEAD " "$MSG_RIGHT_BEHIND" "$local" "$remote"
done < <(git for-each-ref --format="%(refname:short) %(upstream:short)" refs/heads)

if [ "$TOTAL_DIFFERENCES" == 0 ]; then
    echo -e "${CGREEN}Everything is synchronized.$CEND"
fi
