#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# manually start -- should start at login tho
# brew services start yabai

yabai -m config layout bsp

# focus
yabai -m config window_opacity bsp

# visuals
yabai -m config window_shadow off

# mouse
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier        fn             
yabai -m config mouse_action1         move           # left click
yabai -m config mouse_action2         resize         # right hclick
yabai -m config mouse_drop_action     swap

padding=2
yabai -m config top_padding $padding
yabai -m config bottom_padding $padding
yabai -m config left_padding $padding
yabai -m config right_padding $padding
yabai -m config window_gap $padding

yabai -m config                                 \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         4             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

echo "yabai configuration loaded.."
