#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# manually start -- should start at login tho
# brew services start yabai

yabai -m config layout bsp

yabai -m config window_opacity bsp

# focus
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus   off # this causes problems when apps have drag behavior
# focus indicator
# NOTE: colors are 0x{alpha}{Red}{Green}{Blue}
yabai -m config window_border on
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xffbb00ff # purpleish
yabai -m config normal_window_border_color 0xff000000 # black

# visuals
yabai -m config window_shadow off

# mouse
yabai -m config mouse_modifier        fn             
yabai -m config mouse_action1         move           # left click
yabai -m config mouse_action2         resize         # right hclick
yabai -m config mouse_drop_action     swap

padding=0
yabai -m config top_padding $padding
yabai -m config bottom_padding $padding
yabai -m config left_padding $padding
yabai -m config right_padding $padding
yabai -m config window_gap $padding


yabai -m config                                 \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    window_border_width          4              \
    window_border_blur           off            \
    window_border_hidpi          on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            


yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="zoom.us" manage=off
yabai -m rule --add app="^QuickTime Player" manage=off
yabai -m rule --add app="^VoiceOver" manage=off
yabai -m rule --add title=" - Huddle$" manage=off

echo "yabai configuration loaded.."


borders active_color=0xffbb00ff inactive_color=0xff000000 width=8.0 &
